---
- hosts: oel7_prod
  gather_facts: no
  connection: ssh
  
  vars_prompt:
   - name: "hostname"
     prompt: "Enter server hostname or IP"
     private: no
   
   - name: "disk_name"
     prompt: "Disk used for creating partition"
     private: no

   - name: "pvs_name"
     prompt: "Disk name after creating with partition"
     private: no

   - name: "vg_name"
     prompt: "Enter VG name to be created"
     private: no

   - name: "lv_name"
     prompt: "Enter LV name to be created"
     private: no

   - name: "file_system"
     prompt: "Type of file system required?"
     private: no

   - name: "mount_point"
     prompt: "Where need to mount?"
     private: no
    
  tasks:
   - name: Create Partition for "{{ mount_point  }}"  file system
     remote_user: ansible
     become: yes
     become_method: sudo
     shell:
       /bin/echo -e "n\np\n1\n\n\nt\n8e\nw" | sudo fdisk "{{ disk_name }}"

   - name: Create VG for vg_u01
     remote_user: ansible
     become: yes
     become_method: sudo
     lvg:
       vg: "{{ vg_name }}"
       pvs: "{{ pvs_name }}"
       pesize: 8

   - name: Create LVM lv_u01 for "{{ mount_point  }}" file system.
     remote_user: ansible
     become: yes
     become_method: sudo
     lvol:
       vg: "{{ vg_name }}"
       lv: "{{ lv_name }}"
       size: 100%FREE

   - name: Create file system on newly created Logical volume for "{{ mount_point  }}".
     remote_user: ansible
     become: yes
     become_method: sudo
     filesystem:
         fstype: "{{ file_system }}" 
         dev: "/dev/mapper/{{ vg_name }}-{{ lv_name }}"

   - name: Mount the created filesystem
     remote_user: ansible
     become: yes
     become_method: sudo
     mount:
       path: "{{ mount_point }}"
       src: "/dev/mapper/{{ vg_name }}-{{ lv_name }}"
       fstype: "{{ file_system }}"
       opts: rw,noatime,noexec,nodev,nosuid
       state: mounted 
