---
- hosts: "{{ hosts_prompt }}"
  remote_user: your_username
  become: yes
  become_method: sudo
  
  vars_prompt:
    - name: "hosts_prompt"
      prompt: "hostname or host group need to run with Playbook"
      private: no

  tasks:

    - name: Copy the Splunk Forwarder RPM to remote Servers.
      copy:
         src: /home/ansibleadmin/splunkforwarder-6.6.3-e21ee54bc796-linux-2.6-x86_64.rpm
         dest: /home/your_username/
         owner: your_username
         group: your_username
         mode: 0644
 
    - name: Install Splunk Forwarder RPM package on remote servers.
      yum: state=present name={{ item }}
      with_items:
            - /home/your_username/splunkforwarder-6.6.3-e21ee54bc796-linux-2.6-x86_64.rpm 

    - name: Copy the Splunk Forwarder config from your centralized server to remote servers.
      copy:
        src: /home/ansibleadmin/splunk_forwarder_output/
        dest: /opt/splunkforwarder/etc/system/
        directory_mode: yes
        owner: splunk
        group: splunk
        mode: 0600

    - name: Start Splunk forwarder service.
      remote_user: your_username
      become: yes
      become_method: sudo
      become_user: splunk
      shell:
        /opt/splunkforwarder/bin/splunk start --accept-license

    - name: Check Splunk forwarder service.
      command:
        /opt/splunkforwarder/bin/splunk status
      register: service_splunk_status

    - name: Report Splunk forwarder Status.
      debug:
         var: service_splunk_status.stdout_lines
...
